#!/bin/bash
# Provides:         packagesrc        
# Description:      downloads the given source package from the osgrid.org homepage and patches the necessary
#                   changes into the sources and creates a new package
# Author:           Akira Sonoda <akira.sonoda.1@gmail.com>
# Version:          1.3
#
# History:          1.0 - Initial Version
#                   1.1 - includes the omv modules
#                   1.2 - Two packages are created now one original sim and one aki-fork (sittarget patch)
#                   1.3 - Removed some functionality
VERSION=$1
SRCDIR=/home/opensim/src

cd $SRCDIR

# copying the correct tag into an extra directory
cp -R $SRCDIR/akisim  $SRCDIR/$VERSION

# remove the .git folder
cd $SRCDIR/$VERSION
rm -R -f .git
cd $SRCDIR


# Copy module source
cp -R $SRCDIR/osprofile/trunk/OpenSimProfile $SRCDIR/$VERSION/addon-modules
cp -R $SRCDIR/ossearch/trunk/OpenSimSearch $SRCDIR/$VERSION/addon-modules

tar cfz $VERSION.tar.gz $VERSION
cp $VERSION.tar.gz /srv/www/vhosts/suai.dyndns.org

echo package prepared and uploaded
