#!/bin/bash
# Provides:         aki_grid
# Description:      Start script for Robust services
# Author:           Akira Sonoda <akira.sonoda.1@gmail.com>
# Version:          1.0
#
SIMTAG=$1
SIMPATH=/home/opensim/$SIMTAG/bin
MONO_THREADS_PER_CPU=150

PATH="/home/opensim/bin/mono19/bin:$PATH"
PKG_CONFIG_PATH="/home/opensim/bin/mono19/lib/pkgconfig:$PKG_CONFIG_PATH"
MANPATH="/home/opensim/bin/mono19/share/man:$MANPATH"
LD_LIBRARY_PATH="/home/opensim/bin/mono19/lib:$LD_LIBRARY_PATH"

env > /tmp/$SIMTAG.settings.txt
mono --version > /tmp/$SIMTAG.mono.txt

#
# Function which starts the robust server
#
do_start()
{
    # Return
	cd $SIMPATH
	screen -S $SIMTAG -d -m mono-sgen Robust.exe
}

#
# Function which stops the robust server
#
do_stop()
{
    # Return
	cd $SIMPATH
	screen -S $SIMTAG -p 0 -X stuff $"quit"
	screen -S $SIMTAG -p 0 -X eval $"stuff ^M"
}

#
# Function which restarts the robust server
#

case "$2" in
  start)
    do_start
    ;;
  stop)
    do_stop
    ;;
  restart)
    do_stop
	do_start
    ;;
  *)
    echo "Usage: $SCRIPTNAME {SIMTAG} {start|stop|restart}" >&2
    exit 3
    ;;
esac

exit 0
