#!/bin/bash
# Provides:         opensim
# Description:      Start script for opensim services
# Author:           Akira Sonoda <akira.sonoda.1@gmail.com>
# Version:          1.0
#
SIMTAG=$1
SIMPATH=/home/opensim/$SIMTAG/bin
MONO_THREADS_PER_CPU=150

env > /tmp/$SIMTAG.settings.txt
mono --version > /tmp/$SIMTAG.mono.txt

#
# Funktion welche den Simulator startet
#
do_start()
{
    # Return
	cd $SIMPATH
	screen -S $SIMTAG -d -m mono-sgen OpenSim.exe
}

#
# Funktion welche den Simulator stoppt
#
do_stop()
{
    # Return
	cd $SIMPATH
	screen -S $SIMTAG -p 0 -X stuff $"login disable"
	screen -S $SIMTAG -p 0 -X eval $"stuff ^M"	
	screen -S $SIMTAG -p 0 -X stuff $"alert general Sim is going to shut down in two minutes"
	screen -S $SIMTAG -p 0 -X eval $"stuff ^M"	
	screen -S $SIMTAG -p 0 -X stuff $"backup"
	screen -S $SIMTAG -p 0 -X eval $"stuff ^M"
	screen -S $SIMTAG -p 0 -X eval $"stuff ^M"
	sleep 60
	screen -S $SIMTAG -p 0 -X stuff $"alert general Sim is going to shut down in one minute"
	screen -S $SIMTAG -p 0 -X eval $"stuff ^M"	
	sleep 30
	screen -S $SIMTAG -p 0 -X stuff $"alert general Sim is going to shut down in 30 seconds"
	screen -S $SIMTAG -p 0 -X eval $"stuff ^M"
	sleep 30
	screen -S $SIMTAG -p 0 -X stuff $"alert general Sim is going to shut down now"
	screen -S $SIMTAG -p 0 -X eval $"stuff ^M"
	sleep 5
	screen -S $SIMTAG -r -m  -X quit
	sleep 60
	process_id=$(cat /tmp/$SIMTAG.pid 2>/dev/null)
	kill -9 $process_id >/dev/null 2>&1
	rm -f /tmp/$SIMTAG.pid	
}

#
# Funktion welche den Simulator neu startet
#

case "$2" in
  start)
    do_start
    ;;
  stop)
    do_stop
    ;;
  restart)
    do_stop
	do_start
    ;;
  *)
    echo "Usage: $SCRIPTNAME {SIMTAG} {start|stop|restart}" >&2
    exit 3
    ;;
esac

exit 0
