#!/bin/bash
mono --aot OpenSim.exe
mono --aot C5.dll
mono --aot CSJ2K.dll
mono --aot DotNetOpenId.dll
mono --aot DotNetOpenMail.dll
mono --aot HttpServer_OpenSim.dll
mono --aot ICSharpCode.SharpZipLib.dll
mono --aot Ionic.Zip.dll
mono --aot log4net.dll
mono --aot MySql.Data.dll
mono --aot NDesk.Options.dll
mono --aot Nini.dll
mono --aot Npgsql.dll
mono --aot Ode.NET.dll
mono --aot OpenMetaverse.dll
mono --aot OpenMetaverse.Rendering.Meshmerizer.dll
mono --aot OpenMetaverse.StructuredData.dll
mono --aot OpenMetaverseTypes.dll
mono --aot OpenSim.Addons.Groups.dll
mono --aot OpenSim.Addons.OfflineIM.dll
mono --aot OpenSim.ApplicationPlugins.LoadRegions.dll
mono --aot OpenSim.ApplicationPlugins.RegionModulesController.dll
mono --aot OpenSim.ApplicationPlugins.RemoteController.dll
mono --aot OpenSim.Capabilities.dll
mono --aot OpenSim.Capabilities.Handlers.dll
mono --aot OpenSim.Data.dll
mono --aot OpenSim.Data.MSSQL.dll
mono --aot OpenSim.Data.MySQL.dll
mono --aot OpenSim.Data.Null.dll
mono --aot OpenSim.Data.PGSQL.dll
mono --aot OpenSim.Data.SQLite.dll
mono --aot OpenSim.Framework.AssetLoader.Filesystem.dll
mono --aot OpenSim.Framework.Communications.dll
mono --aot OpenSim.Framework.Console.dll
mono --aot OpenSim.Framework.dll
mono --aot OpenSim.Framework.Monitoring.dll
mono --aot OpenSim.Framework.RegionLoader.Filesystem.dll
mono --aot OpenSim.Framework.RegionLoader.Web.dll
mono --aot OpenSim.Framework.Serialization.dll
mono --aot OpenSim.Framework.Servers.dll
mono --aot OpenSim.Framework.Servers.HttpServer.dll
mono --aot OpenSimProfile.Modules.dll
mono --aot OpenSim.Region.ClientStack.dll
mono --aot OpenSim.Region.ClientStack.LindenCaps.dll
mono --aot OpenSim.Region.ClientStack.LindenUDP.dll
mono --aot OpenSim.Region.CoreModules.dll
mono --aot OpenSim.Region.DataSnapshot.dll
mono --aot OpenSim.Region.Framework.dll
mono --aot OpenSim.Region.OptionalModules.dll
mono --aot OpenSim.Region.Physics.ConvexDecompositionDotNet.dll
mono --aot OpenSim.Region.Physics.Manager.dll
mono --aot OpenSim.Region.RegionCombinerModule.dll
mono --aot OpenSim.Region.ScriptEngine.Shared.Api.dll
mono --aot OpenSim.Region.ScriptEngine.Shared.Api.Runtime.dll
mono --aot OpenSim.Region.ScriptEngine.Shared.CodeTools.dll
mono --aot OpenSim.Region.ScriptEngine.Shared.dll
mono --aot OpenSim.Region.ScriptEngine.Shared.Instance.dll
mono --aot OpenSim.Region.ScriptEngine.XEngine.Api.Runtime.dll
mono --aot OpenSim.Region.ScriptEngine.XEngine.dll
mono --aot OpenSim.Region.UserStatistics.dll
mono --aot OpenSimSearch.Modules.dll
mono --aot OpenSim.Server.Base.dll
mono --aot OpenSim.Server.Handlers.dll
mono --aot OpenSim.Services.AssetService.dll
mono --aot OpenSim.Services.AuthenticationService.dll
mono --aot OpenSim.Services.AuthorizationService.dll
mono --aot OpenSim.Services.AvatarService.dll
mono --aot OpenSim.Services.Base.dll
mono --aot OpenSim.Services.Connectors.dll
mono --aot OpenSim.Services.FreeswitchService.dll
mono --aot OpenSim.Services.FriendsService.dll
mono --aot OpenSim.Services.GridService.dll
mono --aot OpenSim.Services.HypergridService.dll
mono --aot OpenSim.Services.Interfaces.dll
mono --aot OpenSim.Services.InventoryService.dll
mono --aot OpenSim.Services.LLLoginService.dll
mono --aot OpenSim.Services.MapImageService.dll
mono --aot OpenSim.Services.PresenceService.dll
mono --aot OpenSim.Services.UserAccountService.dll
mono --aot OpenSim.Services.UserProfilesService.dll
mono --aot PrimMesher.dll
mono --aot SmartThreadPool.dll
mono --aot ThreadedClasses.dll
mono --aot Tools.dll
mono --aot Warp3D.dll
mono --aot XMLRPC.dll
