#!/bin/bash
# Provides:         dereos_arriba_package        
# Description:      Just packs the sources and the general scripts into a tar.gz archive and places the archive into
#                   the distribution directory
#
# Author:           Akira Sonoda <akira.sonoda.1@gmail.com>
# Version:          1.0
#
# History:          1.0 - Initial Version
VERSION=$1
SRCDIR=/home/opensim/src

cd $SRCDIR

# copying the correct tag into an extra directory
cp -R $SRCDIR/arribasim-dev  $SRCDIR/$VERSION

# remove the .git folder
cd $SRCDIR/$VERSION
rm -R -f .git
# copy some files into the documents folder
cp -R $SRCDIR/freakisim-dev/doc/* $SRCDIR/$VERSION/doc
cd $SRCDIR

# create the tar.gz and copy it to the distribution directory

tar cfz $VERSION.tar.gz $VERSION
cp $VERSION.tar.gz /srv/www/vhosts/suai.dyndns.org

echo package prepared and uploaded
