#!/bin/bash
#
# THIS SOFTWARE IS PROVIDED BY THE DEVELOPERS ``AS IS'' AND ANY
# EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE CONTRIBUTORS BE LIABLE FOR ANY
# DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
# (c) Akira Sonoda, 2009
# Version: 1.3
#
# Wo ist die aktuelle OpenSim installation?
OSINS="/home/opensim"

cd $OSINS

build_version=$(cat dereos_freaki_build.txt)
old_version=$(cat dereos_freaki_old.txt)

#Vergleiche die aktuelle Version mit der neuen Version
#falls identisch, verlasse das script
if [ "$old_version" = "$build_version" ]; then
  exit
fi

# nicht identisch! Lösch mal die datei "old_version.txt"
rm "dereos_freaki_old_version.txt"
# kopier die Datei "build_version.txt" nach "old_version.txt"
cp "dereos_freaki_build.txt" "dereos_freaki_old.txt"

# Alles erledigt bis zum nächsten mal

