#!/bin/bash
#
# THIS SOFTWARE IS PROVIDED BY THE DEVELOPERS ``AS IS'' AND ANY
# EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE CONTRIBUTORS BE LIABLE FOR ANY
# DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
# This script does the checkout of a given svn version of the opensim simulator 
# and builds it in the directory /opt/opensim. This script is intended to be used
# only on multi-simulator environments where the build is done in /opt/opensim
# prior to the distribution to the productive sims
#
# Prerequisites: keine
#
# (c) Akira Sonoda, 2015
# Version: 1.0
#
# Variablen, welche gesetzt werden
# Wo befindet sich die opensim installation?
OSINS="/home/opensim"
# Wo befindet sich das Backup verzeichnis?
OSBACK="/home/opensim/backup"
# Uebersteuerung
test_version=$1

# Actually we don't need an own built mono version
# PATH="/home/opensim/bin/mono/bin:$PATH"
# PKG_CONFIG_PATH="/home/opensim/bin/mono/lib/pkgconfig:$PKG_CONFIG_PATH"
# MANPATH="/home/opensim/bin/mono/share/man:$MANPATH"
# LD_LIBRARY_PATH="/home/opensim/bin/mono/lib:$LD_LIBRARY_PATH"

mono --version > /tmp/osbuild.mono.txt

cd $OSINS

# Hole die gerade aktuelle Versionsnummer von einem zentralen Ort
# Falls dieser Server nicht verfügbar ist und die neuste Version nicht
# geholt werden kann verlasse das script.
wget -q http://suai.dyndns.org/dereos_freaki_version.txt
if [ ! -e "$OSINS/dereos_freaki_version.txt" ] ; then
  echo "Probably something went wrong with wget"
  exit
fi

# Fülle den Inhalt der Datei "version.txt" ( aktuelle Version ) und 
# "metro_build_version.txt" (installierte Version) in Variablen ab um die 
# beiden Versionen vergleichen zu können.
new_version=$(cat dereos_freaki_version.txt)
old_version=$(cat dereos_freaki_build.txt)

# Vergleiche die aktuelle Version mit der installierten Version.
# Falls beide Versionen identisch sind. lösche die Datei "version.txt"
# und verlasse das script
if [ "$new_version" == "$old_version" ] && [ "$test_version" == "" ]; then
  rm dereos_freaki_version.txt
  exit
fi

if [ "$test_version" != "" ] ; then
  echo $test_version > "/home/opensim/dereos_freaki_version.txt"
fi

echo $new_version

# Die Versionen waren offensichtlich nicht identisch, also bauen wir einen
# neuen Simulator. Falls bereits ein gebauter Simulator existiert, dann verschiebe
# diesen im Backup Verzeichnis, nachdem du den alten backup gelöscht hast.
# TODO Backup Handling

cd $OSINS
if [ "$test_version" != "" ] ; then
  wget http://suai.dyndns.org/$test_version.tar.gz
  tar xvf $test_version.tar.gz
else
  wget http://suai.dyndns.org/$new_version.tar.gz
  tar xvf $new_version.tar.gz
fi

#build the sim 
if [ "$test_version" != "" ] ; then
	cd $OSINS/$test_version
	# Starte den prebuild process
	./runprebuild.sh
	sleep 5
	# Starte den compiler
	xbuild /p:Configuration=Release
else
	cd $OSINS/$new_version
	# Starte den prebuild process
	./runprebuild.sh
	sleep 5
	# Starte den compiler
	xbuild /p:Configuration=Release
fi

# Setze nun die alte Versionsnummer auf die neue Versionsnummer
cd $OSINS

# Wenn die Versionsnummer nicht uebersteuert wurde, so wird sie zur dereos_freaki_build.txt
if [ "$test_version" == "" ] ; then
	rm dereos_freaki_build.txt
	cp dereos_freaki_version.txt dereos_freaki_build.txt
fi 

if [ "$test_version" != "" ] ; then
  echo $test_version > $OSINS/$test_version/version.txt
else
  echo $new_version > $OSINS/$new_version/version.txt
fi

cd $OSINS

echo "Copying the (possibly new) scripts"

# copy the (possibly new) scripts
if [ "$test_version" != "" ] ; then
  cp $OSINS/$test_version/doc/scripts/* $OSINS/bin
else
  cp $OSINS/$new_version/doc/scripts/* $OSINS/bin
fi

# Housekeeping
if [ "$test_version" != "" ] ; then
  rm -f $test_version.tar.gz
  rm dereos_freaki_version.txt
else
  rm -f $new_version.tar.gz
  rm dereos_freaki_version.txt
fi

echo "Finished building the simulator".
