#!/bin/bash
# Provides:         freaki_package        
# Description:      packages the source repository with some external modules into a tar.gz
#                   archive and copeis it to the web server
# Author:           Akira Sonoda <akira.sonoda.1@gmail.com>
# Version:          1.5
#
# History:          1.0 - Initial Version
#                   1.1 - includes the omv modules
#                   1.2 - Two packages are created now one original sim and one aki-fork (sittarget patch)
#                   1.3 - Removed some functionality
#                   1.4 - Change to FreAkiSim
#                   1.5 - Copying the separately built ODE libs to the package

VERSION=$1
SRCDIR=/home/opensim/src

cd $SRCDIR

# copying the correct tag into an extra directory
cp -R $SRCDIR/freakisim  $SRCDIR/$VERSION

# remove the .git folder
cd $SRCDIR/$VERSION
rm -R -f .git
cd $SRCDIR

# Copy ODE libs
cp $SRCDIR/freakisim-extras/bin/Ode.NET.dll $SRCDIR/$VERSION/bin
cp $SRCDIR/freakisim-extras/bin/Ode.NET.dll.config $SRCDIR/$VERSION/bin
cp $SRCDIR/freakisim-extras/bin/lib32/libode.so $SRCDIR/$VERSION/bin/lib32
cp $SRCDIR/freakisim-extras/bin/lib32/ode.dll $SRCDIR/$VERSION/bin/lib32
cp $SRCDIR/freakisim-extras/bin/lib64/libode-x86_64.so $SRCDIR/$VERSION/bin/lib64
cp $SRCDIR/freakisim-extras/bin/lib64/libode.dylib $SRCDIR/$VERSION/bin/lib64
cp $SRCDIR/freakisim-extras/bin/lib64/ode.dll $SRCDIR/$VERSION/bin/lib64

# Copy module source
cp -R $SRCDIR/osprofile/trunk/OpenSimProfile $SRCDIR/$VERSION/addon-modules
cp -R $SRCDIR/ossearch/trunk/OpenSimSearch $SRCDIR/$VERSION/addon-modules

tar cfz $VERSION.tar.gz $VERSION
cp $VERSION.tar.gz /srv/www/vhosts/suai.dyndns.org

echo package prepared and uploaded
