#!/bin/sh
#
# THIS SOFTWARE IS PROVIDED BY THE DEVELOPERS ``AS IS'' AND ANY
# EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE CONTRIBUTORS BE LIABLE FOR ANY
# DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
# (c) Akira Sonoda 2009
# Version: 1.4
# Version: 1.5 runcheck sucht nach "maintain" weil dieses script vom "xx_xx_maintain" script aufgerufen wird
# Version: 1.6 LocalUserStatistics.db wird nun wieder gesichert.
# Version: 1.7 Fix wegen eines Fehlers im running=`ps ax|grep $SCREENID|grep -v grep|grep -v "maintain"|grep -v "osbackup"`
# Version: 1.8 Backup stoppt den Sim nicht mehr ..
# Version: 1.9 LocalUserStatisticDb wird nicht mehr gesichert
# 
# SCREENID = name des Simulators
SCREENID=$1
# OWNERID = name des Sim owners
OWNERID=$2
# BACKUPSERVER = name des Servers auf dem die zweite Sicherung erfolgt
BACKUPSERVER=$3
# Was ist der Name des Log-Files
LOGNAME=$4

# Von wo aus wird OpenSim gestartet
BASE="/home/opensim/$SCREENID/bin"
# Wohin sollen die Backups gesichert werden?
BDIR="/home/opensim/backup/$SCREENID"

# Wenn die SCREENID beim Aufruf nicht mitgegeben wird, dann beendet sich 
# das script hier
if [ -z "$SCREENID" ]; then
    echo "Usage: osbackup {screenid} {ownerid} {backupserver} {logname}" >&2
    exit 3
fi 

# Wenn die OWNERID beim Aufruf nicht mitgegeben wird, dann beendet sich 
# das script hier
if [ -z "$OWNERID" ]; then
    echo "Usage: osbackup {screenid} {ownerid} {backupserver} {logname}" >&2
    exit 3
fi 

# Wenn der Backupserver beim Aufruf nicht mitgegeben wird, dann beendet sich 
# das script hier
if [ -z "$BACKUPSERVER" ]; then
    echo "Usage: osbackup {screenid} {ownerid} {backupserver} {logname}" >&2
    exit 3
fi 

# Wenn die Logname beim Aufruf nicht mitgegeben wird, dann beendet sich 
# das script hier
if [ -z "$LOGNAME" ]; then
    echo "Usage: osbackup {screenid} {ownerid} {backupserver} {logname}" >&2
    exit 3
fi 

# Nun erstellen wir eine Variable mit dem aktuellen Datum im Format: YYYYMMDDHHMMSS
NEWDIR="`/bin/date +"%Y%m%d%H%M%S"`"

 
#Wir kreieren ein neues Verzeichnis im "backup" ordner
mkdir $BDIR/$NEWDIR

# Verschieben der zuvor erstellten Backup Files in das entsprechende neue directory
mv $BDIR/*.xml $BDIR/$NEWDIR
mv $BDIR/*.oar $BDIR/$NEWDIR
mv $BDIR/*.r32 $BDIR/$NEWDIR


# Wir kopieren das ganze Verzeichnis mit den Region.xml ins neu 
# erstellte backup Verzeichnis
cp -r $BASE/Regions $BDIR/$NEWDIR/

# Wir kopieren die wichtigsten Datenbanken in das neu erstellte Backup Verzeichnis
# cp $BASE/OpenSim.db $BDIR/$NEWDIR/
# cp $BASE/LocalUserStatistics.db $BDIR/$NEWDIR/

# Wir kopieren das OpenSim.ini sowie das Verzeichnis config-include in das
# neu erstellte Backup Verzeichnis.
cp $BASE/OpenSim.ini $BDIR/$NEWDIR/
cp -r $BASE/config-include $BDIR/$NEWDIR/

# LocalUserStatistics werden immer noch nur in einer SQLite Datenbank gespeichert
# Dies koennte Probleme beim Upgrade auf Mono 2.6.x geben... sichere sie aber auf 
# Wunsch von Samira dennoch ...
# cp $BASE/LocalUserStatistics.db $BDIR/$NEWDIR/


#Erstelle ein tar.gz file des Backups
cd $BDIR
tar cfz $OWNERID$SCREENID$NEWDIR.tar.gz $NEWDIR

#Verschlüssle das eben erstellte tar.gz file
gpg -e -r $OWNERID $OWNERID$SCREENID$NEWDIR.tar.gz

#Sende das Versclüsselte File an den Backup Server
# scp $SCREENID$NEWDIR.tar.gz.gpg osbackup@suai.nine.ch:$SCREENID$NEWDIR.tar.gz.gpg
scp $OWNERID$SCREENID$NEWDIR.tar.gz.gpg $BACKUPSERVER:$OWNERID$SCREENID$NEWDIR.tar.gz.gpg

#Räume auf
rm $OWNERID$SCREENID$NEWDIR.tar.gz
rm $OWNERID$SCREENID$NEWDIR.tar.gz.gpg

# Backup erledigt
